crab submit -c crab_BEST_Producer_2017_QCD_0_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_1_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_2_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_3_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_4_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_5_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_6_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_7_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_8_cfg.py
crab submit -c crab_BEST_Producer_2017_QCD_9_cfg.py
