crab submit -c crab_BEST_Producer_2018_QCD_0_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_10_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_1_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_2_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_3_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_4_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_5_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_6_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_7_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_8_cfg.py
crab submit -c crab_BEST_Producer_2018_QCD_9_cfg.py
