crab submit -c crab_BEST_Producer_2015_QCD_0_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_1_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_2_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_3_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_4_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_5_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_6_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_7_cfg.py
crab submit -c crab_BEST_Producer_2015_QCD_8_cfg.py
