crab submit -c crab_BEST_Ht_training_1000_cfg.py
crab submit -c crab_BEST_Ht_training_1100_cfg.py
crab submit -c crab_BEST_Ht_training_1200_cfg.py
crab submit -c crab_BEST_Ht_training_1300_cfg.py
crab submit -c crab_BEST_Ht_training_1400_cfg.py
crab submit -c crab_BEST_Ht_training_1500_cfg.py
crab submit -c crab_BEST_Ht_training_1600_cfg.py
crab submit -c crab_BEST_Ht_training_1700_cfg.py
crab submit -c crab_BEST_Ht_training_1800_cfg.py
crab submit -c crab_BEST_Wb_training_1000_cfg.py
crab submit -c crab_BEST_Wb_training_1100_cfg.py
crab submit -c crab_BEST_Wb_training_1200_cfg.py
crab submit -c crab_BEST_Wb_training_1300_cfg.py
crab submit -c crab_BEST_Wb_training_1400_cfg.py
crab submit -c crab_BEST_Wb_training_1500_cfg.py
crab submit -c crab_BEST_Wb_training_1600_cfg.py
crab submit -c crab_BEST_Wb_training_1700_cfg.py
crab submit -c crab_BEST_Wb_training_1800_cfg.py
crab submit -c crab_BEST_Zt_training_1000_cfg.py
crab submit -c crab_BEST_Zt_training_1100_cfg.py
crab submit -c crab_BEST_Zt_training_1200_cfg.py
crab submit -c crab_BEST_Zt_training_1300_cfg.py
crab submit -c crab_BEST_Zt_training_1400_cfg.py
crab submit -c crab_BEST_Zt_training_1500_cfg.py
crab submit -c crab_BEST_Zt_training_1600_cfg.py
crab submit -c crab_BEST_Zt_training_1700_cfg.py
crab submit -c crab_BEST_Zt_training_1800_cfg.py
