crab submit -c crab_BEST_QCD_1000to1500_training_cfg.py
crab submit -c crab_BEST_QCD_1500to2000_training_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_training_cfg.py
crab submit -c crab_BEST_QCD_pt1000_training_cfg.py
crab submit -c crab_BEST_QCD_pt1000to1400_training_cfg.py
crab submit -c crab_BEST_QCD_pt800to1000_training_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_bGenFilter1_training_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_bGenFilter2_training_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_training2_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_training3_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_training4_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_training5_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_enrichedB1_training_cfg.py
crab submit -c crab_BEST_QCD_2000toInf_enrichedB2_training_cfg.py
